name: Feature File CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm install
    - run: npm run features2html:ci
    - uses: MeilCli/slack-upload-file@v1
      id: message
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channels: ${{ secrets.SLACK_CHANNELS }}
        file_path: '/tmp/features.html'
        file_name: 'features.html'
        file_type: 'html'
        initial_comment: 'feature file post by slack-upload-file'
    - run: 'echo ${{ fromJson(steps.message.outputs.response).file.permalink }}'